name = "answerpulse"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"

[placement]
mode = "smart"

[observability]
enabled = true

[vars]
NEXT_PUBLIC_SUPABASE_URL = "https://pxydwoxztgghbwqyqgxk.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_jf8bxalaQmXYtxPWOSjpCg_vlxtYxWT"
NEXT_PUBLIC_PAYPAL_CLIENT_ID = "AYfCuEMTppPDwjwY085IKG_KpADFEmywaPcwIA7hJcrsyD2QmxMjTTjDDaiHUQVoHMftDEsyfzAY8a8n"
NEXT_PUBLIC_PAYPAL_PAYMENT_LINK = "https://www.paypal.com/ncp/payment/QDHG6SJY5MQAJ"
NEXT_PUBLIC_APP_URL = "https://answerpulse.answerpulse-cf.workers.dev"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
not_found_handling = "404-page"
