-- 简易流量追踪表
-- 记录每次页面访问的来源、UTM 参数、路径等基础信息
-- 零依赖方案：无需 cookie、无需用户同意、不影响性能

create table if not exists page_visits (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  
  -- 页面信息
  page_path text not null default '/',
  referrer text,
  user_agent text,
  
  -- UTM 参数
  utm_source text,
  utm_medium text,
  utm_campaign text,
  
  -- 地理位置（从 Cloudflare header 获取）
  ip_country text,
  
  -- 会话标识（每次页面加载生成新 UUID）
  session_id uuid default gen_random_uuid()
);

-- 创建索引以加速常见查询
create index idx_page_visits_created_at on page_visits(created_at desc);
create index idx_page_visits_page_path on page_visits(page_path);
create index idx_page_visits_utm_source on page_visits(utm_source) where utm_source is not null;
create index idx_page_visits_session_id on page_visits(session_id);

-- 启用行级安全（RLS），但允许匿名写入（通过 service_role 绕过）
alter table page_visits enable row level security;

-- 允许任何人读取（公开统计看板用）
create policy "page_visits public read" on page_visits
  for select
  using (true);
